[project]
name = "bill-tagger"
version = "0.1.0"
description = "Assigning policy area tags to federal legislation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.16",
    "asyncio>=3.4.3",
    "ipykernel>=6.29.5",
    "pip>=25.0.1",
]
