name: Training Workflow

on:
  workflow_dispatch:

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run training script
        run: |
          get-data
          uv run src/training/train.py
